### PR TITLE
Reload article text when reading options are closed

### LINKED ISSUE #15: Changing reading options doesn't change current article
The Reading Options (controlling font and font size) have no effect. Nothing crashes, but nothing happens.

Still need to investigate extent. Does this feature not work in previous versions of iOS? Does the app crash in iOS 8? Who knows.

Spotted in f305086

### PR DESCRIPTION
**Pull request by deweytyl**
Closes #15

### CODE REVIEW

File: SandB-iOS/Podfile [hunk 1]
```diff
@@ -1,8 +1,9 @@
 source 'https://github.com/artsy/Specs.git'
 source 'https://github.com/CocoaPods/Specs.git'
 
-platform :ios, '7.0'
+platform :ios, '8.1'
```
Comment (alexthemitchell) [inline SandB-iOS/Podfile]: Why not 8.0?

Comment (deweytyl) [inline SandB-iOS/Podfile]: No reason in particular.

File: SandB-iOS/SandB-iOS/Controllers/ArticlePageViewHolderController.m [hunk 2]
```diff
@@ -53,7 +37,8 @@ - (void)viewDidLoad
     NSArray *viewControllers = @[startingViewController];
     //[self.pageViewController setViewControllers:viewControllers direction:UIPageViewControllerNavigationDirectionForward animated:NO completion:nil];
     
-    // Bug in PageViewController with Scroll. http://stackoverflow.com/questions/13633059/uipageviewcontroller-how-do-i-correctly-jump-to-a-specific-page-without-messing
+    // Bug in PageViewController with Scroll.
```
Comment (alexthemitchell) [inline SandB-iOS/SandB-iOS/Controllers/ArticlePageViewHolderController.m]: Is this still true?

File: SandB-iOS/SandB-iOS/Controllers/ArticlePageViewHolderController.m [hunk 3]
```diff
@@ -129,71 +112,24 @@ - (void)didReceiveMemoryWarning
...
-{
-    self.fontSize = [[NSUserDefaults standardUserDefaults] floatForKey:@"ReadingOptionsFontSize"];
-    self.fontFamily = [[NSUserDefaults standardUserDefaults] objectForKey:@"ReadingOptionsFontFamily"];
-    self.isLightTheme = [[NSUserDefaults standardUserDefaults] boolForKey:@"ReadingOptionsIsLightTheme"];
-}
-
 #pragma mark - Page View Controller methods
 
-- (ArticleViewController *) viewControllerAtIndex:(NSUInteger) index {
+- (ArticleViewController *)viewControllerAtIndex:(NSUInteger) index {
```
Comment (alexthemitchell) [inline SandB-iOS/SandB-iOS/Controllers/ArticlePageViewHolderController.m]: Put the space back (style guide nit)

File: SandB-iOS/SandB-iOS/Controllers/ArticleViewController.m [hunk 4]
```diff
@@ -5,194 +5,121 @@
...
+
+#define NUMBER_ARTICLE_ROWS 3
+
+#define TITLE_ROW_INDEX 0
+#define CATEGORY_ROW_INDEX 1
+#define CONTENT_ROW_INDEX 2
+
+#define TITLE_ROW_HEIGHT 70.0f
+#define CATEGORY_ROW_HEIGHT 10.0f
+#define CONTENT_ROW_HEIGHT contentHeight + 10
```
Comment (alexthemitchell) [inline SandB-iOS/SandB-iOS/Controllers/ArticleViewController.m:25]: Thank you.

File: SandB-iOS/Podfile (hunk 1 above)
Comment (alexthemitchell) [inline SandB-iOS/Podfile]: Let's target 8.0 then, just in case somebody's afraid of that .1 release.

File: SandB-iOS/SandB-iOS/Controllers/ArticlePageViewHolderController.m (hunk 2 above)
Comment (deweytyl) [inline SandB-iOS/SandB-iOS/Controllers/ArticlePageViewHolderController.m]: I'll look into it

File: SandB-iOS/SandB-iOS/Controllers/ArticlePageViewHolderController.m (hunk 3 above)
Comment (deweytyl) [inline SandB-iOS/SandB-iOS/Controllers/ArticlePageViewHolderController.m]: Seems like most of of the methods here have no space. Do you want me to change all of them?

Comment (alexthemitchell) [inline SandB-iOS/SandB-iOS/Controllers/ArticlePageViewHolderController.m]: Yes please.

Comment (deweytyl) [inline SandB-iOS/SandB-iOS/Controllers/ArticlePageViewHolderController.m]: In the entire project or just this file? And for future reference, what should we use as a style guide?

File: SandB-iOS/SandB-iOS/Controllers/ArticlePageViewHolderController.m (hunk 2 above)
Comment (deweytyl) [inline SandB-iOS/SandB-iOS/Controllers/ArticlePageViewHolderController.m]: I can't find the bug anymore. Will use the simpler code

File: SandB-iOS/SandB-iOS/Controllers/ArticlePageViewHolderController.m (hunk 3 above)
Comment (deweytyl) [inline SandB-iOS/SandB-iOS/Controllers/ArticlePageViewHolderController.m]: And most the style guides have no space, either their or between the type and index
